language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - npm run lint
  - npm run test
  - ng e2e
  - ng run web:build:production --configuration=production --base-href https://philly-vanilly.github.io/clients-for-reddit/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/apps/web
  on:
    branch: master
